package org.gridchem.client;
/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/

/* The following code was generated by JFlex 1.3.5 on 5/8/02 2:38 AM */

/* Complete Basis Set (CBS) Keyword &
   CBSExtrapolate Keyword
   Last Update: 6/26/2001 
   http://www.gaussian.com/00000420.htm
   http://www.gaussian.com/00000421.htm
*/


 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 5/8/02 2:38 AM from the specification file
 * <tt>file:/w:/home/jj-lee/Java/edu/uiuc/ncsa/Parsers/cbs.flex</tt>
 */

import org.gridchem.client.*;
import org.gridchem.client.common.Settings;

public class CBS {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int IGNOREALL = 3;
  final public static int FLOATVAL = 1;
  final public static int YYINITIAL = 0;
  final public static int INTVAL = 2;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    35,  0,  0,  0,  0,  0,  0,  0,  8,  9,  0,  3,  0, 13,  4,  0, 
     1,  2, 34, 17, 14,  2,  2,  2,  2,  2,  0,  0,  0, 21,  0,  0, 
     0, 23, 11, 10, 27,  5,  7, 30, 33, 26,  0, 36, 15, 22, 29, 18, 
    19, 16, 28, 12, 20, 31,  0,  0, 24, 25, 32,  0,  0,  0,  0,  0, 
     0, 23, 11, 10, 27,  5,  7, 30, 33, 26,  0, 36, 15, 22, 29, 18, 
    19, 16, 28, 12, 20, 31,  0,  0, 24, 25, 32,  0,  6,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    37,    74,   111,   148,   185,   222,   259,   296,   333, 
      370,   407,   444,   481,   518,   555,   592,   629,   666,   666, 
      703,   740,   777,   814,   851,   888,   925,   962,   999,  1036, 
     1073,  1110,  1147,  1184,   592,  1221,  1258,  1295,  1332,  1369, 
     1406,  1443,  1480,  1517,  1554,  1591,  1628,  1665,  1702,  1739, 
     1776,   259,  1813,  1850,  1887,  1924,  1961,  1998,  2035,  2072, 
     2109,  2146,  2183,  2220,  2257,  2294,  2331,  2368,  2405,  2442, 
     2479,  2516,   666,  2553,  2590,   148,  2627,  2664,  2701,  2738, 
     2775,  2812,  2849,  2886,  2923,  2960,  2997,  3034,  3071,  3108, 
      148,  3145,  3182,  3219,  3256,  3293,  3330,  3367,  3404,  3441, 
     3478,  3515,  3552,  3589,  3626,   148,  3663,  3700,  3737,  3774, 
     3811,  3848,  3885,  3922,  3959,  3996,  4033,  4070,  4107,  4144, 
     4181,  4218,  4255,  4292,  4329,  4366,   148,  4403,  4440,  4477, 
     4514,  4551,  4588,  4625,   148,  4662,  4699,  4736,  4773,  4810, 
     4847,  4884,  4921,  4958,  4995,  5032,   148,  5069,  5106,  5143, 
     5180,  5217,  5254,  5291,  5328,   148,  5365,  5402,  5439,   148
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\5\5\1\6\4\5\1\7\1\10\4\5\1\11\1\5"+
    "\1\12\1\13\1\14\5\5\1\15\1\16\1\17\1\20"+
    "\10\5\2\21\1\22\2\5\1\22\6\5\1\22\1\21"+
    "\2\5\1\21\20\5\1\21\3\5\2\23\1\24\2\5"+
    "\1\24\6\5\1\24\1\23\2\5\1\23\20\5\1\23"+
    "\47\5\55\0\1\25\47\0\1\26\53\0\1\27\34\0"+
    "\1\30\55\0\1\31\43\0\1\32\11\0\1\33\15\0"+
    "\1\34\74\0\1\35\14\0\1\36\44\0\1\37\61\0"+
    "\1\40\3\0\1\41\5\0\1\42\11\0\2\43\1\0"+
    "\1\44\11\0\1\43\2\0\1\43\20\0\1\43\3\0"+
    "\2\43\13\0\1\43\2\0\1\43\20\0\1\43\3\0"+
    "\2\23\13\0\1\23\2\0\1\23\20\0\1\23\16\0"+
    "\1\45\7\0\1\46\13\0\1\47\20\0\1\50\61\0"+
    "\1\51\45\0\1\52\36\0\1\53\43\0\1\40\26\0"+
    "\1\54\65\0\1\55\42\0\1\56\30\0\1\57\50\0"+
    "\1\60\12\0\1\61\34\0\1\62\57\0\1\63\25\0"+
    "\1\64\7\0\1\65\22\0\2\44\2\0\2\66\7\0"+
    "\1\44\2\0\1\44\11\0\1\66\6\0\1\44\14\0"+
    "\1\67\73\0\1\70\26\0\1\71\36\0\1\72\43\0"+
    "\1\40\44\0\1\73\55\0\1\74\33\0\1\75\53\0"+
    "\1\76\46\0\1\77\24\0\1\100\4\0\1\101\5\0"+
    "\1\102\5\0\1\103\3\0\1\104\36\0\1\105\53\0"+
    "\1\106\33\0\1\107\57\0\1\110\31\0\1\32\23\0"+
    "\2\23\1\111\2\0\1\111\6\0\1\111\1\23\2\0"+
    "\1\23\20\0\1\23\11\0\1\112\42\0\1\113\44\0"+
    "\1\112\55\0\1\114\1\115\1\116\57\0\1\53\37\0"+
    "\1\117\32\0\1\120\35\0\1\121\75\0\1\122\34\0"+
    "\1\123\31\0\1\124\43\0\1\125\55\0\1\126\56\0"+
    "\1\127\36\0\1\130\47\0\1\131\24\0\1\132\57\0"+
    "\1\133\30\0\1\134\67\0\1\135\30\0\1\114\37\0"+
    "\1\136\27\0\1\137\30\0\1\140\54\0\1\141\41\0"+
    "\1\142\44\0\1\143\33\0\1\144\35\0\1\145\62\0"+
    "\1\145\33\0\1\146\20\0\1\145\26\0\1\145\54\0"+
    "\1\147\24\0\1\150\57\0\1\151\42\0\1\152\45\0"+
    "\1\153\37\0\1\114\30\0\1\154\1\0\1\155\1\156"+
    "\64\0\1\157\50\0\1\160\37\0\1\161\47\0\1\162"+
    "\44\0\1\163\23\0\1\164\51\0\1\165\52\0\1\114"+
    "\42\0\1\166\41\0\1\114\54\0\1\167\52\0\1\170"+
    "\43\0\1\171\11\0\1\172\55\0\1\173\37\0\1\174"+
    "\63\0\1\175\53\0\1\114\45\0\1\176\35\0\1\177"+
    "\30\0\1\174\57\0\1\200\37\0\1\201\32\0\1\202"+
    "\16\0\1\203\25\0\1\204\102\0\1\205\32\0\1\206"+
    "\40\0\1\207\56\0\1\210\37\0\1\211\34\0\1\212"+
    "\33\0\1\213\67\0\1\214\51\0\1\215\10\0\1\216"+
    "\103\0\1\217\12\0\1\213\66\0\1\220\22\0\1\221"+
    "\55\0\1\222\46\0\1\223\55\0\1\224\35\0\1\225"+
    "\60\0\1\226\12\0\1\227\40\0\1\227\66\0\1\230"+
    "\22\0\1\231\70\0\1\227\32\0\1\232\32\0\1\233"+
    "\64\0\1\234\36\0\1\235\41\0\1\114\53\0\1\224"+
    "\56\0\1\236\20\0\1\237\40\0\1\202\64\0\1\240"+
    "\17\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  0,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0, 
     0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /* user code: */
  public static boolean DEBUG = false;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CBS(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CBS(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[5476];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 134: 
          { if (Settings.DEBUG) System.out.println(yytext());
	       yybegin(FLOATVAL);
   }
        case 161: break;
        case 126: 
          { if (Settings.DEBUG) System.out.println(yytext());
	      yybegin(FLOATVAL);
   }
        case 162: break;
        case 75: 
          { if (Settings.DEBUG) System.out.println(yytext());
   }
        case 163: break;
        case 77: 
          { if (Settings.DEBUG) System.out.println(yytext());
   }
        case 164: break;
        case 155: 
          { if (Settings.DEBUG) System.out.println(yytext());
		  yybegin(FLOATVAL);
   }
        case 165: break;
        case 146: 
          { if (Settings.DEBUG) System.out.println(yytext());
		 yybegin(FLOATVAL);
   }
        case 166: break;
        case 159: 
          { if (Settings.DEBUG) System.out.println(yytext());
		    yybegin(FLOATVAL);
   }
        case 167: break;
        case 18: 
          { if (Settings.DEBUG) System.out.println(yytext());
	   yybegin(YYINITIAL);
   }
        case 168: break;
        case 35: 
          { if (Settings.DEBUG) System.out.println(yytext());
	   yybegin(YYINITIAL);
   }
        case 169: break;
        case 105: 
          { if (Settings.DEBUG) System.out.println(yytext());
	     yybegin(FLOATVAL);
   }
        case 170: break;
        case 90: 
          { if (Settings.DEBUG) System.out.println(yytext());
		 yybegin(INTVAL);
   }
        case 171: break;
        case 4: 
        case 5: 
        case 6: 
        case 7: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
          {  }
        case 172: break;
        case 16: 
        case 17: 
        case 19: 
          {  }
        case 173: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            return YYEOF;
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java CBS <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        CBS scanner = null;
        try {
          scanner = new CBS( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
