package org.gridchem.client;
import java.util.*;
import java.io.*;

import org.gridchem.client.common.Settings;
import org.gridchem.client.util.*;

// Program to describe the connectivity
// this is very rudimentary. 
// Dodi Heryadi 11/13/2002
 
public class Connect
{
   public Connect(String temporary) 
   {

//First create table for covalent radii, based on the atomic number
        double rad[] = new double[107];
        rad[0] = 0.000;
        rad[1] = 0.230;
        rad[2] = 0.700;
	rad[3] = 0.680;
	rad[4] = 0.350;
	rad[5] = 0.830;
	rad[6] = 0.680;
	rad[7] = 0.680;
	rad[8] = 0.680;
	rad[9] = 0.640;
	rad[10] = 0.700;
	rad[11] = 0.970;
	rad[12] = 1.100;
	rad[13] = 1.350;
	rad[14] = 1.200;
	rad[15] = 0.750;
	rad[16] = 1.020;
	rad[17] = 0.990;
	rad[18] = 0.700;
	rad[19] = 1.330;



// open the input file generated by FinalCoordParser or GFinalCoordParser
     FileInput in = new FileInput(temporary) ;
//
        double x[] = new double[20];  
        double y[] = new double[20];
        double z[] = new double[20];
        int ctr[] = new int[20];
        int atom[] = new int[20];
        int k = -1;
        char c = in.readCharacter();
        while ( !in.eof())
     {
       k++;
       int l = in.readInteger() ;
//      System.out.println("center was: " + l) ;
       ctr[k] = l;
       int l1 = in.readInteger() ;
//      System.out.println("atom number was: " + l1) ;
       atom[k] = l1;

       double d = in.readDouble() ;
       x[k] = d;
//      System.out.println("x was: " + x[k]) ;
       double f = in.readDouble() ;
       y[k] = f;
//      System.out.println("y was: " + y[k]) ;
       double f1 = in.readDouble() ;
       z[k] = f1;
//      System.out.println("z was: " + z[k]) ;
//      System.out.println("index: " +k);
      }
     in.close() ;
//     System.out.println("final index: " +k);
      
/*     for (int i1 = 0; i1 < k; i1++)
     { System.out.println("CENTER: " +ctr[i1]);
       System.out.println("  atom: " +atom[i1]);
       System.out.println("     x: " +x[i1]);
       System.out.println("     y: " +y[i1]);
       System.out.println("     z: " +z[i1]);
     }
*/
// now find the distance among the atoms: Rij
       double dist[][] = new double[20][20];

       for (int i2 = 0; i2 < k; i2++)
         {
          for (int j2 = 0; j2 < k; j2++)
            {
              if (i2 != j2)
                 {
                     double xdiff = (x[i2] - x[j2])*(x[i2] - x[j2]);
                     double ydiff = (y[i2] - y[j2])*(y[i2] - y[j2]); 
                     double zdiff = (z[i2] - z[j2])*(z[i2] - z[j2]);  
                     double xyz = xdiff + ydiff + zdiff;
                     dist[i2][j2] = Math.sqrt(xyz);
                    System.out.println("i2       : " +i2);
                     System.out.println("   j2    : " +j2);
                     System.out.println("     dist: " +dist[i2][j2]); 
                 }
             }
           }

//create a file to store the connectivity information
     try 
     {
       //ParseGSCF2 temp = new ParseGSCF2(Settings.defaultDirStr + 
    		   ParseGSCF2 temp = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "connect");
// now start the connection
/*     System.out.println(" ");
      System.out.println(" "); */
       for (int i2 = 0; i2 < k; i2++)
         {
           System.out.println("CONNECT   " +ctr[i2]);
           if (ctr[i2] > 9 && ctr[i2] < 100)
           { temp.putField("CONNECT   ");
           temp.putField(ctr[i2]);
           }
           else if (ctr[i2] > 99 && ctr[i2] < 1000)
           { temp.putField("CONNECT  ");
           temp.putField(ctr[i2]);
           }
           else{
        	   temp.putField("CONNECT    ");
               temp.putField(ctr[i2]);
           } 
             
            
          for (int j2 = 0; j2 < k; j2++)
            {
//             System.out.println("   ");
              if (i2 != j2)
                 {
                   double test = rad[atom[i2]] + rad[atom[j2]] + 0.200 ;
                   double test1 = Math.sqrt(test);
                   if (dist[i2][j2] < test1 ) {
                     System.out.println("                 " +ctr[j2]);
                     if (ctr[j2] > 9 && ctr[j2] < 100)
                     { temp.putField("   ");
                     temp.putField(ctr[j2]);
                     }
                     else if (ctr[j2] > 99 && ctr[j2] < 1000)
                     { temp.putField("  ");
                     temp.putField(ctr[j2]);
                     }
                     else{
                    	 temp.putField("    ");
                         temp.putField(ctr[j2]);
                     }  
                     
                       }
                 }
             }
             temp.putField("\n");
           }
      }
      catch (IOException ie) {System.out.println("Error in Connectivity");}
   }
}

