package org.gridchem.client;

/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Oct 29 09:10:13 CST 2002
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
import org.gridchem.client.*;

public class FinalCoordSym {
  /* terminals */
  public static final int ENERGY = 11;
  public static final int EOF = 0;
  public static final int ITERATION = 10;
  public static final int INPUT7 = 14;
  public static final int error = 1;
  public static final int INPUT6 = 13;
  public static final int INPUT5 = 12;
  public static final int INPUT4 = 9;
  public static final int SCFDONE = 4;
  public static final int INPUT3 = 8;
  public static final int FOUNDITER = 3;
  public static final int INPUT2 = 7;
  public static final int DASH2 = 6;
  public static final int INPUT1 = 2;
  public static final int DASH1 = 5;
}

