/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/

/* The following code was generated by JFlex 1.3.5 on 10/21/02 12:00 PM */
package org.gridchem.client;

import org.gridchem.client.*;
import org.gridchem.client.common.Settings;

import java_cup.*;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 10/21/02 12:00 PM from the specification file
 * <tt>file:/home/dodi/new_qcrjm/gaussian/g1.flex</tt>
 */
public class G1Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int FLOATMP3 = 11;
  final public static int ITER2 = 2;
  final public static int FLOATMP2 = 10;
  final public static int FLOATMP1 = 9;
  final public static int MPOPT = 8;
  final public static int INTMP = 12;
  final public static int INTVALUE = 3;
  final public static int IGNOREALL = 2;
  final public static int ITER = 1;
  final public static int YYINITIAL = 0;
  final public static int MP2 = 7;
  final public static int FLOAT2 = 6;
  final public static int FLOAT1 = 5;
  final public static int FLOATVALUE = 4;
  final public static int ITER3 = 2;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    14,  0,  0,  0,  0,  0,  0,  0, 29,  7,  0,  3,  0, 46,  4,  1, 
     2, 48, 44, 47,  2,  2, 45,  2,  2,  2, 27,  0,  0,  6,  0,  0, 
     0,  0,  0, 24, 26, 28, 25, 49, 31, 41,  0,  0, 42, 32,  8, 36, 
    43,  0, 30, 23,  5, 50,  0,  0,  0,  0,  0,  0,  0,  0,  0, 40, 
     0, 33, 11, 35, 39, 12, 16,  0, 22, 20,  0,  0, 38, 10, 21, 15, 
    19,  0, 13, 17, 18,  9,  0,  0, 34,  0, 37,  0,  3,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    51,   102,   153,   204,   255,   306,   357,   408,   459, 
      510,   561,   612,   663,   714,   765,   816,   867,   918,   969, 
     1020,  1020,  1071,  1122,  1173,  1224,  1275,  1326,  1377,  1428, 
     1479,  1530,  1581,  1632,  1683,  1734,  1785,  1836,  1887,  1938, 
     1989,  2040,  2091,  2091,  2142,  2193,  2244,  2295,  2346,  2397, 
     2448,  1071,  2499,  1173,  2550,  1275,  2601,  2652,  2703,  2754, 
     2805,  2856,  2907,  2958,  3009,  1785,  3060,  1887,  3111,  1989, 
     3162,  3213,  3264,  3315,  3366,  3417,  3468,  3519,  2499,  2550, 
     2601,  3570,  3621,  3672,  3723,  3774,  3825,  3876,  3927,  3060, 
     3111,  3162,  3978,  4029,  4080,  4131,  4182,  4233,  4284,  4335, 
     4386,  4437,  4488,  4539,  4590,  4641,  4692,  4743,  4794,  4845, 
     4896,  4947,  4998,  5049,  5100,  5151,  5202,  5253,  5304,  5355, 
     5406,  5457,  5508,  5559,  5610,  5661,  5712,  5763,  5814,  5865, 
     5916,  5967,  6018,  6069,  6120,  6171,  6222,  6273,  6324,  6375, 
     6426,  6477,  6528,  6579,  6630,  6681,  6732,  6783,  6834,  6885, 
     6936,  6987,  7038,  7089,  7140,  7191,  7242,  7293,  7344,  7395, 
     7446,  7497,  7548,   663,  7599,  7650,  7701,  7752,  7803,  7854, 
     7905,  7956,  8007,  8058,  8109,  8160,  8211,  8262,  8313,  8364, 
     8415,  8466,  8517,  8568,  8619,  8670,  8721,  8772,  8823,  8874, 
     8925,  8976,  9027,  9078,  9129,  9180,  9231,   663,  9282,  9333, 
     9384,  9435,  9486,  9537,  9588,   663,  9639,  9690,  9741,  9792, 
     9843,  9894,  9945,  9996, 10047, 10098, 10149, 10200, 10251, 10302, 
    10353, 10404, 10455, 10506,   663,   663, 10557, 10608, 10659, 10710, 
      663,   663, 10761, 10812, 10863, 10914, 10965, 11016, 11067, 11118, 
    11169, 11220,   663, 11271, 11322,   663, 11373,   663, 11424, 11475, 
    11526, 11577, 11628, 11679, 11730, 11781, 11832, 11883, 11934, 11985, 
    12036, 12087,   663, 12138, 12189,   663, 12240, 12291, 12342, 12393, 
    12444, 12495, 12546, 12597, 12648,   663,   663, 12699, 12750, 12801, 
    12852,   663
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\10\16\1\17\57\16\1\20\21\16\1\21\6\16\1\22"+
    "\1\16\1\23\3\16\1\24\103\16\1\25\1\26\50\16"+
    "\2\25\1\26\2\25\4\16\1\27\1\30\50\16\2\27"+
    "\1\30\2\27\4\16\1\31\1\32\50\16\2\31\1\32"+
    "\2\31\4\16\1\33\1\34\50\16\2\33\1\34\2\33"+
    "\7\16\1\35\32\16\1\36\27\16\1\37\21\16\1\40"+
    "\4\16\1\41\1\16\1\42\1\16\1\43\3\16\1\44"+
    "\20\16\1\45\1\46\50\16\2\45\1\46\2\45\4\16"+
    "\1\47\1\50\50\16\2\47\1\50\2\47\4\16\1\51"+
    "\1\52\50\16\2\51\1\52\2\51\4\16\1\53\1\54"+
    "\50\16\2\53\1\54\2\53\2\16\74\0\1\55\110\0"+
    "\1\56\45\0\1\57\5\0\1\60\72\0\1\61\63\0"+
    "\1\62\44\0\1\63\41\0\1\25\51\0\2\25\1\0"+
    "\2\25\4\0\1\64\1\0\1\65\47\0\2\64\1\0"+
    "\2\64\4\0\1\64\51\0\2\64\1\0\2\64\4\0"+
    "\1\66\1\0\1\67\47\0\2\66\1\0\2\66\4\0"+
    "\1\66\51\0\2\66\1\0\2\66\4\0\1\70\1\0"+
    "\1\71\47\0\2\70\1\0\2\70\4\0\1\70\51\0"+
    "\2\70\1\0\2\70\41\0\1\72\76\0\1\73\46\0"+
    "\1\74\45\0\1\75\122\0\1\76\40\0\1\77\63\0"+
    "\1\100\44\0\1\101\41\0\1\102\1\0\1\103\47\0"+
    "\2\102\1\0\2\102\4\0\1\102\51\0\2\102\1\0"+
    "\2\102\4\0\1\104\1\0\1\105\47\0\2\104\1\0"+
    "\2\104\4\0\1\104\51\0\2\104\1\0\2\104\4\0"+
    "\1\106\1\0\1\107\47\0\2\106\1\0\2\106\4\0"+
    "\1\106\51\0\2\106\1\0\2\106\4\0\1\53\51\0"+
    "\2\53\1\0\2\53\14\0\1\110\104\0\1\111\42\0"+
    "\1\112\77\0\1\113\60\0\1\114\75\0\1\115\42\0"+
    "\1\116\42\0\1\117\51\0\2\117\1\0\2\117\4\0"+
    "\1\120\51\0\2\120\1\0\2\120\4\0\1\121\51\0"+
    "\2\121\1\0\2\121\36\0\1\122\102\0\1\123\42\0"+
    "\1\124\42\0\1\125\106\0\1\126\51\0\1\127\75\0"+
    "\1\130\42\0\1\131\42\0\1\132\51\0\2\132\1\0"+
    "\2\132\4\0\1\133\51\0\2\133\1\0\2\133\4\0"+
    "\1\134\51\0\2\134\1\0\2\134\15\0\1\135\117\0"+
    "\1\136\35\0\1\137\55\0\1\140\62\0\1\141\70\0"+
    "\1\142\62\0\1\143\106\0\1\144\47\0\1\145\75\0"+
    "\1\146\35\0\1\147\112\0\1\150\25\0\1\151\70\0"+
    "\1\152\62\0\1\153\52\0\1\154\102\0\1\155\44\0"+
    "\1\156\76\0\1\157\46\0\1\160\56\0\1\161\62\0"+
    "\1\162\104\0\1\163\57\0\1\164\65\0\1\165\44\0"+
    "\1\166\120\0\1\167\24\0\1\170\56\0\1\171\62\0"+
    "\1\172\65\0\1\173\55\0\1\174\77\0\1\175\54\0"+
    "\1\176\61\0\1\177\55\0\1\200\75\0\1\201\46\0"+
    "\1\202\63\0\1\203\61\0\1\204\77\0\1\205\53\0"+
    "\1\206\62\0\1\207\55\0\1\210\75\0\1\211\54\0"+
    "\1\212\76\0\1\213\41\0\1\214\76\0\1\215\53\0"+
    "\1\216\56\0\1\217\115\0\1\220\47\0\1\221\76\0"+
    "\1\222\46\0\1\223\41\0\1\224\57\0\1\225\72\0"+
    "\1\226\56\0\1\227\115\0\1\230\34\0\1\231\113\0"+
    "\1\232\24\0\1\233\64\0\1\234\64\0\1\235\62\0"+
    "\1\236\105\0\1\237\71\0\1\240\60\0\1\241\64\0"+
    "\1\242\24\0\1\243\66\0\1\244\62\0\1\245\62\0"+
    "\1\246\105\0\1\247\41\0\1\250\106\0\1\251\31\0"+
    "\1\252\102\0\1\253\60\0\1\254\62\0\1\255\53\0"+
    "\1\256\104\0\1\257\25\0\1\260\117\0\1\261\31\0"+
    "\1\262\100\0\1\263\62\0\1\264\53\0\1\265\56\0"+
    "\1\266\75\0\1\267\45\0\1\270\64\0\1\271\63\0"+
    "\1\272\62\0\1\273\67\0\1\274\67\0\1\275\32\0"+
    "\1\276\112\0\1\277\45\0\1\300\65\0\1\301\62\0"+
    "\1\302\67\0\1\303\57\0\1\304\111\0\1\305\27\0"+
    "\1\306\63\0\1\307\61\0\1\310\62\0\1\311\64\0"+
    "\1\312\113\0\1\313\67\0\1\314\55\0\1\315\27\0"+
    "\1\316\62\0\1\317\62\0\1\320\64\0\1\321\65\0"+
    "\1\322\71\0\1\323\65\0\1\324\71\0\1\325\62\0"+
    "\1\326\44\0\1\327\66\0\1\330\107\0\1\331\35\0"+
    "\1\332\74\0\1\333\62\0\1\334\44\0\1\335\51\0"+
    "\1\336\117\0\1\337\46\0\1\340\41\0\1\341\62\0"+
    "\1\342\64\0\1\343\115\0\1\344\70\0\1\345\54\0"+
    "\1\346\25\0\1\347\62\0\1\350\64\0\1\351\67\0"+
    "\1\352\111\0\1\353\46\0\1\354\67\0\1\355\71\0"+
    "\1\356\70\0\1\357\54\0\1\360\53\0\1\361\40\0"+
    "\1\362\75\0\1\363\65\0\1\364\42\0\1\365\77\0"+
    "\1\366\107\0\1\367\35\0\1\370\45\0\1\371\61\0"+
    "\1\372\75\0\1\373\43\0\1\374\105\0\1\375\37\0"+
    "\1\376\74\0\1\377\45\0\1\u0100\76\0\1\u0101\106\0"+
    "\1\u0102\36\0\1\u0103\64\0\1\u0104\53\0\1\u0105\112\0"+
    "\1\u0106\23\0\1\u0107\121\0\1\u0108\32\0\1\u0109\52\0"+
    "\1\u010a\70\0\1\u010b\62\0\1\u010c\70\0\1\u010d\62\0"+
    "\1\u010e\62\0\1\u010f\66\0\1\u0110\50\0\1\u0111\62\0"+
    "\1\u0112\72\0\1\u0113\105\0\1\u0114\62\0\1\u0115\34\0"+
    "\1\u0116\57\0\1\u0117\61\0\1\u0118\56\0\1\u0119\76\0"+
    "\1\u011a\35\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1, 
     1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9,  9,  0,  0,  0,  0,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  9,  0,  0,  9,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  9,  0,  0,  9,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  9,  0,  0,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  public static boolean DEBUG = false;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public G1Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public G1Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[12903];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 276: 
          { 
     yybegin(IGNOREALL);
      return new Symbol(G1Sym.MPDONE); }
        case 283: break;
        case 262: 
          { 
  if (Settings.DEBUG) System.out.println("G1Flex: Found MP2(Full)");
            yybegin(MPOPT);
            return new Symbol(G1Sym.MPStart); }
        case 284: break;
        case 163: 
          { 
       if (Settings.DEBUG) System.out.println("G1Flex: Found MP2 energy");
               yybegin(FLOATMP1);
              return new Symbol(G1Sym.MPEnerg); }
        case 285: break;
        case 224: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found RMS Force");
            yybegin(FLOAT2);
            return new Symbol(G1Sym.RmsGrad1); }
        case 286: break;
        case 230: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found RMS Force");
            yybegin(FLOATMP3);
            return new Symbol(G1Sym.MPRms); }
        case 287: break;
        case 247: 
          { 
if (Settings.DEBUG) System.out.println("G1Flex: MPDONE, THE_END_OF_FILE");
     yybegin(IGNOREALL);
      return new Symbol(G1Sym.MPDONE); }
        case 288: break;
        case 245: 
          { 
if (Settings.DEBUG) System.out.println("G1Flex: MPStart, THE_END_OF_FILE");
     yybegin(MPOPT);
      return new Symbol(G1Sym.MPStart); }
        case 289: break;
        case 197: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found the Step number");
   yybegin(INTVALUE);
   return new Symbol(G1Sym.NSearch1); }
        case 290: break;
        case 80: 
          { 
  if (Settings.DEBUG) System.out.println("G1Flex: Found the RMS force");   
if (Settings.DEBUG) System.out.println(yytext());
   yybegin(ITER);
   return new Symbol(G1Sym.RGRAD1, new Float(yytext())); }
        case 291: break;
        case 20: 
          { 
  if  (Settings.DEBUG) System.out.println("G1Flex: Found iteration");
   if (Settings.DEBUG) System.out.println(yytext());
  yybegin (ITER);
   return new Symbol(G1Sym.ITERATION1, new Integer(yytext()));
 }
        case 292: break;
        case 79: 
          { 
  if (Settings.DEBUG) System.out.println("G1lex: Found the maximum force");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(ITER);
   return new Symbol(G1Sym.MGRAD1, new Float(yytext())); }
        case 293: break;
        case 90: 
          { 
  if (Settings.DEBUG) System.out.println("G1Flex: Found the maximum force");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(MPOPT);
   return new Symbol(G1Sym.MPMGRAD, new Float(yytext())); }
        case 294: break;
        case 281: 
          { 
    if (Settings.DEBUG) System.out.println("G1lex: Found Number of steps");
	   yybegin(ITER);
	   return new Symbol(G1Sym.FOUNDITER1); 
   }
        case 295: break;
        case 275: 
          { 
if (Settings.DEBUG) System.out.println("G1Flex: SCFDONE1, Optimization completed"); 
     yybegin(MP2);
      return new Symbol(G1Sym.SCFDONE1); }
        case 296: break;
        case 205: 
          { 
if (Settings.DEBUG) System.out.println("G1Flex: Found the Step number for MP");
   yybegin(INTMP);
   return new Symbol(G1Sym.NMP); }
        case 297: break;
        case 265: 
          { 
       if (Settings.DEBUG) System.out.println("G1Flex: Found the energy in ITER");
               yybegin(FLOATVALUE);
              return new Symbol(G1Sym.Energ1); }
        case 298: break;
        case 231: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found Maximum Force");
            yybegin(FLOATMP2);
            return new Symbol(G1Sym.MPMax); }
        case 299: break;
        case 225: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found Maximum Force");
            yybegin(FLOAT1);
            return new Symbol(G1Sym.MaxGrad1); }
        case 300: break;
        case 91: 
          { 
  if (Settings.DEBUG) System.out.println("G1Flex: Found the RMS force");   
if (Settings.DEBUG) System.out.println(yytext());
   yybegin(MPOPT);
   return new Symbol(G1Sym.MPRGRAD, new Float(yytext())); }
        case 301: break;
        case 242: 
          { 
if (Settings.DEBUG) System.out.println("G1Flex: SCFDONE1, THE_END_OF_FILE");
     yybegin(MP2);
      return new Symbol(G1Sym.SCFDONE1); }
        case 302: break;
        case 42: 
          { 
  if  (Settings.DEBUG) System.out.println("G1Flex: Found iteration");
   if (Settings.DEBUG) System.out.println(yytext());
  yybegin (MPOPT);
   return new Symbol(G1Sym.MPITER, new Integer(yytext())); }
        case 303: break;
        case 89: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found the energy");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(MPOPT);
   return new Symbol(G1Sym.MPENERGY, new Float(yytext())); }
        case 304: break;
        case 78: 
          { 
   if (Settings.DEBUG) System.out.println("G1Flex: Found the energy in FLOATVALUE");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(ITER);
   return new Symbol(G1Sym.ENERGY1, new Float(yytext())); }
        case 305: break;
        case 30: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
          {  }
        case 306: break;
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
          {  }
        case 307: break;
        case 13: 
        case 14: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 43: 
          {  }
        case 308: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] class_fields = sym.class.getFields();
      for (int i = 0; i < class_fields.length; i++) {
        if (class_fields[i].getInt(null) == token) {
          return class_fields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java G1Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        G1Lexer scanner = null;
        try {
          scanner = new G1Lexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
