/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Oct 14 11:16:46 CDT 2002
//----------------------------------------------------

package org.gridchem.client;

import java_cup.runtime.*;
import javax.swing.*;

import org.gridchem.client.*;
import org.gridchem.client.common.Settings;
import org.gridchem.client.util.*;
import org.gridchem.client.gui.panels.*;
import org.gridchem.client.gui.panels.myccg.job.JobPanel;

import java.util.*;
import java.io.*;

/** CUP v0.10j generated parser.
  * @version Mon Oct 14 11:16:46 CDT 2002
  */
public class G1Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public G1Parser() {super();}

  /** Constructor which sets the default scanner. */
  public G1Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\025\000\002\003\007\000\002\002\004\000\002\004" +
    "\003\000\002\005\004\000\002\005\003\000\002\021\002" +
    "\000\002\006\006\000\002\022\002\000\002\007\007\000" +
    "\002\010\004\000\002\011\004\000\002\012\004\000\002" +
    "\013\003\000\002\014\004\000\002\014\003\000\002\023" +
    "\002\000\002\016\006\000\002\024\002\000\002\015\007" +
    "\000\002\017\004\000\002\020\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\004\004\005\001\002\000\004\007\012\001" +
    "\002\000\004\007\uffff\001\002\000\004\002\007\001\002" +
    "\000\004\002\000\001\002\000\006\005\027\007\012\001" +
    "\002\000\006\005\ufffd\007\ufffd\001\002\000\004\022\013" +
    "\001\002\000\004\006\ufffc\001\002\000\004\006\016\001" +
    "\002\000\006\005\ufffb\007\ufffb\001\002\000\004\020\017" +
    "\001\002\000\004\010\ufffa\001\002\000\004\010\022\001" +
    "\002\000\004\011\024\001\002\000\004\023\023\001\002" +
    "\000\004\011\ufff8\001\002\000\004\024\026\001\002\000" +
    "\006\005\ufff9\007\ufff9\001\002\000\006\005\ufff7\007\ufff7" +
    "\001\002\000\004\012\031\001\002\000\006\005\ufffe\007" +
    "\ufffe\001\002\000\004\014\ufff5\001\002\000\004\017\054" +
    "\001\002\000\004\014\035\001\002\000\006\014\035\017" +
    "\ufff6\001\002\000\004\025\037\001\002\000\006\014\ufff3" +
    "\017\ufff3\001\002\000\004\013\ufff2\001\002\000\004\013" +
    "\041\001\002\000\004\021\043\001\002\000\006\014\ufff1" +
    "\017\ufff1\001\002\000\004\015\ufff0\001\002\000\004\015" +
    "\046\001\002\000\004\016\051\001\002\000\004\026\047" +
    "\001\002\000\004\016\uffee\001\002\000\006\014\uffef\017" +
    "\uffef\001\002\000\004\027\052\001\002\000\006\014\uffed" +
    "\017\uffed\001\002\000\006\014\ufff4\017\ufff4\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\006\003\005\004\003\001\001\000\006\005" +
    "\007\006\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\027\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\013\001\001\000\004" +
    "\007\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\017\001\001\000\004\010\020\001\001\000\004" +
    "\011\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\031\013\032\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\033\016\035\001\001" +
    "\000\004\016\052\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\023\037\001\001\000\004\015\041\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\043\001" +
    "\001\000\004\017\044\001\001\000\004\020\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$G1Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions() throws IOException
    {
      action_obj = new CUP$G1Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$G1Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$G1Parser$actions {

 
  //__________________________________
  public static boolean DEBUG = true;
       public ParseGSCF2 temp1;
    public ParseGSCF2 temp2;
   public ParseGSCF2 temp3;
        public ParseGSCF2 temp4;
    public ParseGSCF2 temp5;
   public ParseGSCF2 temp6;
  private static JTable table;               
  private static final String tableLabel = "SCF Intermediate Results:";
// private static String cycle = "0";
 
  
  public static JTable getTable() {
    return table;
  }

  public static String getTableLabel() {
    return tableLabel;
  }

//   }

  private final G1Parser parser;

  /** Constructor */
  CUP$G1Parser$actions(G1Parser parser) throws IOException{
    this.parser = parser;

   //temp1 = new ParseGSCF2(Settings.defaultDirStr + 
	temp1 = new ParseGSCF2(Env.getApplicationDataDir() +
     		Settings.fileSeparator + "Energy_data");
    //temp2 = new ParseGSCF2(Settings.defaultDirStr +
    temp2 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary2");
    //temp3 = new ParseGSCF2(Settings.defaultDirStr +
   	temp3 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary3");
    temp1.putField("TitleText: Energy versus Iteration"+" - "+JobPanel.jobName+"\n");
    temp1.putField("XLabel: Iteration\n YLabel: Energy\n");
    temp1.putField("DataSet: Energy\n");
     temp1.putField("1, ");
    temp2.putField("TitleText: Gradient versus Iteration"+" - "+JobPanel.jobName+"\n");
    temp2.putField("XLabel: Iteration\n YLabel: Maximum Gradient\n");
    temp2.putField("DataSet: Maximum Gradient\n");
    temp3.putField("\n\n");
    temp3.putField("XLabel: Iteration\n YLabel: RMS Gradient\n");
    temp3.putField("DataSet: RMS Gradient\n");

   //temp4 = new ParseGSCF2(Settings.defaultDirStr + 
   temp4 = new ParseGSCF2(Env.getApplicationDataDir() +
     		Settings.fileSeparator + "Gradient_data");
    //temp5 = new ParseGSCF2(Settings.defaultDirStr + 
    temp5 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary5");
    //temp6 = new ParseGSCF2(Settings.defaultDirStr +
    temp6 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary6");
    temp4.putField("TitleText: Energy versus Iteration\n");
    temp4.putField("XLabel: Iteration\n YLabel: Energy\n");
    temp4.putField("DataSet: Energy\n");
     temp4.putField("1, ");
    temp5.putField("TitleText: Gradient versus Iteration\n");
    temp5.putField("XLabel: Iteration\n YLabel: Maximum Gradient\n");
    temp5.putField("DataSet: Maximum Gradient\n");
    temp6.putField("\n\n");
    temp6.putField("XLabel: Iteration\n YLabel: RMS Gradient\n");
    temp6.putField("DataSet: RMS Gradient\n");
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$G1Parser$do_action(
    int                        CUP$G1Parser$act_num,
    java_cup.runtime.lr_parser CUP$G1Parser$parser,
    java.util.Stack            CUP$G1Parser$stack,
    int                        CUP$G1Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$G1Parser$result;

      /* select the action based on the action number */
      switch (CUP$G1Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // force2 ::= MPRms MPRGRAD 
            {
              Object RESULT = null;
		int mprgleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int mprgright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float mprg = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:g1: MP RMS Force "+mprg);
             float mprg1 = mprg.floatValue();
             temp6.putField(mprg1);

              CUP$G1Parser$result = new java_cup.runtime.Symbol(14/*force2*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // force1 ::= MPMax MPMGRAD 
            {
              Object RESULT = null;
		int mpmgleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int mpmgright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float mpmg = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:g1: MP Maximum Force "+mpmg);
        float mpmg1 = mpmg.floatValue();
        temp5.putField(mpmg1);
              CUP$G1Parser$result = new java_cup.runtime.Symbol(13/*force1*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // mpcycle ::= NMP MPITER NT$3 force1 force2 
            {
              Object RESULT = null;
              // propagate RESULT from NT$3
              if ( ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value;
		int itleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).left;
		int itright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).right;
		Integer it = (Integer)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).value;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(11/*mpcycle*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$3 ::= 
            {
              Object RESULT = null;
		int itleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int itright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Integer it = (Integer)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:g1:  MP ITERATION "+it);
     int cycl1 = it.intValue();
      temp4.putField(cycl1+1);
      temp4.putField(", ");
      temp5.putField(cycl1);
      temp5.putField(", ");
      temp6.putField(cycl1);
      temp6.putField(", ");
 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(18/*NT$3*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // mpcycle1 ::= MPEnerg MPENERGY NT$2 mpcycle 
            {
              Object RESULT = null;
              // propagate RESULT from NT$2
              if ( ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).value;
		int mpenleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).left;
		int mpenright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).right;
		Float mpen = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(12/*mpcycle1*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$2 ::= 
            {
              Object RESULT = null;
		int mpenleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int mpenright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float mpen = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:g1:  ENERGY "+mpen);
                   float energ1 = mpen.floatValue();
                   energ1 = 100*energ1;
            temp4.putField(energ1);

              CUP$G1Parser$result = new java_cup.runtime.Symbol(17/*NT$2*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // mppat ::= mpcycle1 
            {
              Object RESULT = null;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(10/*mppat*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // mppat ::= mppat mpcycle1 
            {
              Object RESULT = null;
		
  if (DEBUG) System.out.println("CUP:g1: in mppat");
 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(10/*mppat*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // mpintro ::= MPStart 
            {
              Object RESULT = null;
		
   if (DEBUG) System.out.println("CUP:g1: MPSTart ");
 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(9/*mpintro*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // mp2 ::= mpintro mppat 
            {
              Object RESULT = null;
		
    if (DEBUG) System.out.println("CUP:g1: in mp2 mpintro mppat");
 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(8/*mp2*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // grad2 ::= RmsGrad1 RGRAD1 
            {
              Object RESULT = null;
		int rgleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int rgright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float rg = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt: RMS Force "+rg);
     float rg1 = rg.floatValue();
     temp3.putField(rg1);
 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(7/*grad2*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // grad1 ::= MaxGrad1 MGRAD1 
            {
              Object RESULT = null;
		int mgleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int mgright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float mg = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt: Maximum Force "+mg);
         float maxim = mg.floatValue();
   temp2.putField(maxim);       

              CUP$G1Parser$result = new java_cup.runtime.Symbol(6/*grad1*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cycle ::= NSearch1 ITERATION1 NT$1 grad1 grad2 
            {
              Object RESULT = null;
              // propagate RESULT from NT$1
              if ( ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).value;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(5/*cycle*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$1 ::= 
            {
              Object RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt:  ITERATION "+c); 
              int cycl = c.intValue();
      temp1.putField(cycl+1);
      temp1.putField(", ");
      temp2.putField(cycl);
      temp2.putField(", ");
      temp3.putField(cycl);
      temp3.putField(", "); 


              CUP$G1Parser$result = new java_cup.runtime.Symbol(16/*NT$1*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // scfcycle ::= Energ1 ENERGY1 NT$0 cycle 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-2)).value;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(4/*scfcycle*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt:  ENERGY "+e);
    float energ = e.floatValue();
            temp1.putField(energ); 

              CUP$G1Parser$result = new java_cup.runtime.Symbol(15/*NT$0*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // scfpat ::= scfcycle 
            {
              Object RESULT = null;

              CUP$G1Parser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // scfpat ::= scfpat scfcycle 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt: in scfpat"); 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // scfintro ::= FOUNDITER1 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt:  found the start of Iteration"); 
              CUP$G1Parser$result = new java_cup.runtime.Symbol(2/*scfintro*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= startpt EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).value;
		RESULT = start_val;
              CUP$G1Parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$G1Parser$parser.done_parsing();
          return CUP$G1Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // startpt ::= scfintro scfpat SCFDONE1 mp2 MPDONE 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt:  end of parse tree "); 
 	     
              CUP$G1Parser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$G1Parser$stack.elementAt(CUP$G1Parser$top-0)).right, RESULT);
            }
          return CUP$G1Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

