package org.gridchem.client;
/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Oct 31 13:49:25 CST 2002
//----------------------------------------------------

import java_cup.runtime.*;
import javax.swing.*;

import org.gridchem.client.*;

import java.util.*;
import java.io.*;

/** CUP v0.10j generated parser.
  * @version Thu Oct 31 13:49:25 CST 2002
  */
public class GFinalCoordParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public GFinalCoordParser() {super();}

  /** Constructor which sets the default scanner. */
  public GFinalCoordParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\003\005\000\002\002\004\000\002\004" +
    "\004\000\002\005\004\000\002\005\003\000\002\006\007" +
    "\000\002\007\003\000\002\010\003\000\002\011\003\000" +
    "\002\012\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\004\006\005\001\002\000\004\005\011\001" +
    "\002\000\004\004\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\000\001\002\000\004\005\uffff\001\002\000" +
    "\004\010\017\001\002\000\006\005\011\007\014\001\002" +
    "\000\006\005\ufffd\007\ufffd\001\002\000\004\002\001\001" +
    "\002\000\006\005\ufffe\007\ufffe\001\002\000\004\011\020" +
    "\001\002\000\004\011\ufffb\001\002\000\004\012\ufffa\001" +
    "\002\000\004\012\022\001\002\000\004\013\ufff9\001\002" +
    "\000\004\013\024\001\002\000\006\005\ufff8\007\ufff8\001" +
    "\002\000\006\005\ufffc\007\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\006\003\005\004\003\001\001\000\006\005" +
    "\011\006\012\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\015\001" +
    "\001\000\004\006\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\022\001\001" +
    "\000\002\001\001\000\004\012\024\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GFinalCoordParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions() throws IOException
    {
      action_obj = new CUP$GFinalCoordParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GFinalCoordParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$GFinalCoordParser$actions {

 
  //__________________________________
  public static boolean DEBUG = true;
  public ParseGSCF2a temp;
  public int ini;
  private static JTable table;               
  private static final String tableLabel = "SCF Intermediate Results:";
// private static String cycle = "0";
 
  
  public static JTable getTable() {
    return table;
  }

  public static String getTableLabel() {
    return tableLabel;
  }


  private final GFinalCoordParser parser;

  /** Constructor */
  CUP$GFinalCoordParser$actions(GFinalCoordParser parser) throws IOException {
    this.parser = parser;
     temp = new ParseGSCF2a("finalcoord.pdb");
     ini = 0;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$GFinalCoordParser$do_action(
    int                        CUP$GFinalCoordParser$act_num,
    java_cup.runtime.lr_parser CUP$GFinalCoordParser$parser,
    java.util.Stack            CUP$GFinalCoordParser$stack,
    int                        CUP$GFinalCoordParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GFinalCoordParser$result;

      /* select the action based on the action number */
      switch (CUP$GFinalCoordParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // inp6 ::= INPUT6 
            {
              Object RESULT = null;
		int e6left = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left;
		int e6right = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right;
		Float e6 = (Float)((java_cup.runtime.Symbol) CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).value;
      float zcoor = e6.floatValue();
      double zca = 0.52918*zcoor;
      double zc = zca*1000;
      float zc1 = Math.round(zc);
      float zcoor1 = zc1/1000;
      if (zcoor1 >= 0.0) {temp.putField(" ");}
      if (zcoor1 == 0.0) {temp.putField("0.000");}
      else {temp.putField(zcoor1);}
     temp.putField("\n");

              CUP$GFinalCoordParser$result = new java_cup.runtime.Symbol(8/*inp6*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // inp5 ::= INPUT5 
            {
              Object RESULT = null;
		int e5left = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left;
		int e5right = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right;
		Float e5 = (Float)((java_cup.runtime.Symbol) CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).value;

      float ycoor = e5.floatValue();
      double yca = 0.52918*ycoor;
      
       double yc = yca*1000;
      float yc1 = Math.round(yc);
      float ycoor1 = yc1/1000;
      if (ycoor1 >= 0.0) {temp.putField(" ");}
      if (ycoor1 == 0.0) {temp.putField("0.000");}
      else {temp.putField(ycoor1);}
      temp.putField("  ");

              CUP$GFinalCoordParser$result = new java_cup.runtime.Symbol(7/*inp5*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // inp4 ::= INPUT4 
            {
              Object RESULT = null;
		int e4left = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right;
		Float e4 = (Float)((java_cup.runtime.Symbol) CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).value;
      float xcoor = e4.floatValue();
     double xca = 0.52918*xcoor;
     double xc = xca*1000;
      float xc1 = Math.round(xc);
      float xcoor1 = xc1/1000;
      if (xcoor1 >= 0.0) {temp.putField(" ");}
      if (xcoor1 == 0.0) {temp.putField("0.000");}
      else {temp.putField(xcoor1);}
      temp.putField("  ");

              CUP$GFinalCoordParser$result = new java_cup.runtime.Symbol(6/*inp4*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // inp3 ::= INPUT3 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).value;
     ini = ini + 1;
     temp.putField("ATOM      ");
    temp.putField(ini);
    temp.putField("  ");

      float atom = e.floatValue();
      if (atom == 6.0) { temp.putField("C       1          ");}
      else if (atom == 1.0) { temp.putField("H       1          ");}
        else if (atom == 8.0) { temp.putField("O       1          ");}
      else if (atom == 2.0) { temp.putField("He       1         ");}
      else if (atom == 3.0) { temp.putField("Li       1         ");}
      else if (atom == 4.0) { temp.putField("Be       1         ");}
      else if (atom == 5.0) { temp.putField("B       1          ");}
      else if (atom == 7.0) { temp.putField("N       1          ");}
      else if (atom == 9.0) { temp.putField("F       1          ");}
      else if (atom == 10.0) { temp.putField("Ne       1          ");}
      else if (atom == 11.0) { temp.putField("Na       1          "); 
      //temp1.putField(11);}
      }
      else if (atom == 12.0) { temp.putField("Mg       1          ");
      //temp1.putField(12);}
      }
      else if (atom == 13.0) { temp.putField("Al       1          ");
      //temp1.putField(13);}
      }
      else if (atom == 14.0) { temp.putField("Si       1          ");
      //temp1.putField(14);}
      }
      else if (atom == 15.0) { temp.putField("P        1          ");
      //temp1.putField(15);}
      }
      else if (atom == 16.0) { temp.putField("S        1          ");
      //temp1.putField(16);}
      }
      else if (atom == 17.0) { temp.putField("Cl       1          ");
      //temp1.putField(17);}
      }
      else if (atom == 18.0) { temp.putField("Ar       1          ");
      //temp1.putField(18);}
      }
      else if (atom == 19.0) { temp.putField("K        1          ");
      //temp1.putField(19);}
      }
      else if (atom == 20.0) { temp.putField("Ca       1          ");
      //temp1.putField(20);}
      }
      else if (atom == 21.0) { temp.putField("Sc       1          ");
      //temp1.putField(21);}
      }
      else if (atom == 22.0) { temp.putField("Ti       1          ");
      //temp1.putField(22);}
      }
      else if (atom == 23.0) { temp.putField("V        1          ");
      //temp1.putField(23);}
      }
      else if (atom == 24.0) { temp.putField("Cr       1          ");
      //temp1.putField(24);}
      }
      else if (atom == 25.0) { temp.putField("Mn       1          ");
      //temp1.putField(25);}
      }
      else if (atom == 26.0) { temp.putField("Fe       1          ");
      //temp1.putField(26);}
      }
      else if (atom == 27.0) { temp.putField("Co       1          ");
      //temp1.putField(27);}
      }
      else if (atom == 28.0) { temp.putField("Ni       1          ");
      //temp1.putField(28);}
      }
      else if (atom == 29.0) { temp.putField("Cu       1          ");
      //temp1.putField(29);}
      }
      else if (atom == 30.0) { temp.putField("Zn       1          ");
      //temp1.putField(30);}
      }
      else if (atom == 31.0) { temp.putField("Ga       1          ");
      //temp1.putField(31);}
      }
      else if (atom == 32.0) { temp.putField("Ge       1          ");
      //temp1.putField(32);}
      }
      else if (atom == 33.0) { temp.putField("As       1          ");
      //temp1.putField(33);}
      }
      else if (atom == 34.0) { temp.putField("Se       1          ");
      //temp1.putField(34);}
      }
      else if (atom == 35.0) { temp.putField("Br       1          ");
      //temp1.putField(35);}
      }
      else if (atom == 36.0) { temp.putField("Kr       1          ");
      //temp1.putField(36);}
      }
      else if (atom == 37.0) { temp.putField("Rb       1          ");
      //temp1.putField(37);}
      }
      else if (atom == 38.0) { temp.putField("Sr       1          ");
      //temp1.putField(38);}
      }
      else if (atom == 39.0) { temp.putField("Y        1          ");
      //temp1.putField(39);}
      }
      else if (atom == 40.0) { temp.putField("Zr       1          ");
      //temp1.putField(40);}
      }
      else if (atom == 41.0) { temp.putField("Nb       1          ");
      //temp1.putField(41);}
      }
      else if (atom == 42.0) { temp.putField("Mo       1          ");
      //temp1.putField(42);}
      }
      else if (atom == 43.0) { temp.putField("Tc       1          ");
      //temp1.putField(43);}
      }
      else if (atom == 44.0) { temp.putField("Ru       1          ");
      //temp1.putField(44);}
      }
      else if (atom == 45.0) { temp.putField("Rh       1          ");
      //temp1.putField(45);}
      }
      else if (atom == 46.0) { temp.putField("Pd       1          ");
      //temp1.putField(46);}
      }
      else if (atom == 47.0) { temp.putField("Ag       1          ");
      //temp1.putField(47);}
      }
      else if (atom == 48.0) { temp.putField("Cd       1          ");
      //temp1.putField(48);}
      }
      else if (atom == 49.0) { temp.putField("In       1          ");
      //temp1.putField(49);}
      }
      else if (atom == 50.0) { temp.putField("Sn       1          ");
      //temp1.putField(50);}
      }
      else if (atom == 51.0) { temp.putField("Sb       1          ");
      //temp1.putField(51);}
      }
      else if (atom == 52.0) { temp.putField("Te       1          ");
      //temp1.putField(52);}
      }
      else if (atom == 53.0) { temp.putField("I        1          ");
      //temp1.putField(53);}
      }
      else if (atom == 54.0) { temp.putField("Xe       1          ");
      //temp1.putField(54);}
      }
      else if (atom == 55.0) { temp.putField("Cs       1          ");
      //temp1.putField(55);}
      }
      else if (atom == 56.0) { temp.putField("Ba       1          ");
      //temp1.putField(56);}
      }
      else if (atom == 57.0) { temp.putField("La       1          ");
      //temp1.putField(57);}
      }
      else if (atom == 58.0) { temp.putField("Ce       1          ");
      //temp1.putField(58);}
      }
      else if (atom == 59.0) { temp.putField("Pr       1          ");
      //temp1.putField(59);}
      }
      else if (atom == 60.0) { temp.putField("Nd       1          ");
      //temp1.putField(60);}
      }
      else if (atom == 61.0) { temp.putField("Pm       1          ");
      //temp1.putField(61);}
      }
      else if (atom == 72.0) { temp.putField("Hf       1          ");
      //temp1.putField(72);}
      }
      else if (atom == 73.0) { temp.putField("Ta       1          ");
      //temp1.putField(73);}
      }
      else if (atom == 74.0) { temp.putField("W        1          ");
      //temp1.putField(74);}
      }
      else if (atom == 75.0) { temp.putField("Re       1          ");
      //temp1.putField(75);}
      }
      else if (atom == 76.0) { temp.putField("Os       1          ");
      //temp1.putField(76);}
      }
      else if (atom == 77.0) { temp.putField("Ir       1          ");
      //temp1.putField(77);}
      }
      else if (atom == 78.0) { temp.putField("Pt       1          ");
      //temp1.putField(78);}
      }
      else if (atom == 79.0) { temp.putField("Au       1          ");
      //temp1.putField(79);}
      }
      else if (atom == 80.0) { temp.putField("Hg       1          ");
      //temp1.putField(80);}
      }
      else if (atom == 81.0) { temp.putField("Tl       1          ");
      //temp1.putField(81);}
      }
      else if (atom == 82.0) { temp.putField("Pb       1          ");
      //temp1.putField(82);}
      }
      else if (atom == 83.0) { temp.putField("Bi       1          ");
      //temp1.putField(83);}
      }
      else if (atom == 84.0) { temp.putField("Po       1          ");
      //temp1.putField(84);}
      }
      else if (atom == 85.0) { temp.putField("At       1          ");
      //temp1.putField(85);}
      }
      else if (atom == 86.0) { temp.putField("Rn       1          ");
      //temp1.putField(86);}
      }
      else if (atom == 87.0) { temp.putField("Fr       1          ");
      //temp1.putField(87);}
      }
            
              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(5/*inp3*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // scfcycle ::= INPUT2 inp3 inp4 inp5 inp6 
            {
              Object RESULT = null;

              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(4/*scfcycle*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // scfpat ::= scfcycle 
            {
              Object RESULT = null;

              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // scfpat ::= scfpat scfcycle 
            {
              Object RESULT = null;

              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // scfintro ::= FOUNDITER INPUT1 
            {
              Object RESULT = null;

              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(2/*scfintro*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= startpt EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).value;
		RESULT = start_val;
              CUP$GFinalCoordParser$result = 
            	  new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$GFinalCoordParser$parser.done_parsing();
          return CUP$GFinalCoordParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // startpt ::= scfintro scfpat SCFDONE 
            {
              Object RESULT = null;

              CUP$GFinalCoordParser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$GFinalCoordParser$stack.elementAt(CUP$GFinalCoordParser$top-0)).right, RESULT);
            }
          return CUP$GFinalCoordParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

