/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
/* The following code was generated by JFlex 1.3.5 on 10/25/02 10:16 AM */

package org.gridchem.client;
import org.gridchem.client.*;
import org.gridchem.client.common.Settings;

import java_cup.*;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 10/25/02 10:16 AM from the specification file
 * <tt>file:/home/dodi/new_qcrjm/gaussian/gmcscfa.flex</tt>
 */
public class GMCSCFaLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int ITER2 = 3;
  final public static int DASH = 5;
  final public static int INTVALUE = 1;
  final public static int SCF1 = 1;
  final public static int IGNOREALL = 1;
  final public static int ITER = 2;
  final public static int YYINITIAL = 0;
  final public static int ITER8 = 4;
  final public static int ITER7 = 10;
  final public static int ITER6 = 9;
  final public static int ITER5 = 8;
  final public static int FLOATVALUE = 6;
  final public static int ITER4 = 7;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    11,  0,  0,  0,  0,  0,  0,  0, 19,  6,  0,  3,  0, 25,  4,  0, 
     1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0,  0,  0,  0,  0,  0, 
     0, 13,  0, 23, 18,  9,  5, 16,  0,  7,  0,  0, 14, 21, 15, 12, 
    24, 22, 10, 20,  8,  0, 26,  0,  0, 17,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    27,    54,    81,   108,   135,   162,   189,   216,   243, 
      270,   297,   324,   297,   351,   378,   297,   405,   432,   459, 
      486,   297,   513,   540,   567,   594,   621,   648,   675,   702, 
      729,   756,   783,   810,   432,   837,   864,   513,   891,   567, 
      918,   621,   945,   675,   972,   729,   999,  1026,  1053,   837, 
     1080,  1107,   918,   945,   972,   999,  1134,  1161,  1188,  1215, 
     1242,  1269,  1296,  1323,  1350,  1377,  1404,  1431,  1458,  1485, 
     1512,  1539,  1566,  1593,  1620,  1647,  1674,  1701,  1728,  1755, 
     1782,  1809,  1836,  1863,  1890,  1917,  1944,  1971,  1998,  2025, 
     2052,  2079,  2106,  2133,  2160,  2187,  2214,  2241,  2268,  2295, 
     2322,  2349,  2376,  2403,  2430,  2457,  2484,  2511,  2538,   297, 
     2565,   297,  2592,  2619,  2646,  2673,  2700,   297,  2727,  2754, 
     2781,  2808,  2835,  2862,  2889,  2916,  2943,  2970,  2997,  3024, 
     3051,  3078,  3105,  3132,  3159,  3186,  3213,  3240,  3267,  3294, 
     3321,  3348,  3375,  3402,  3429,  3456,  3483,  3510,  3537,  3564, 
     3591,  3618,  3645,  3672,  3699,  3726,  3753,  3780,  3807,  3834, 
     3861,  3888,  3915,  3942,  3969,  3996,  4023,   297
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\7\14\1\15\57\14\1\16\1\17\26\14\1\20\2\14"+
    "\1\21\1\22\31\14\2\23\1\24\25\14\1\24\17\14"+
    "\1\25\14\14\1\26\3\27\25\26\1\30\1\26\1\14"+
    "\2\31\1\32\25\14\1\32\2\14\2\33\1\34\25\14"+
    "\1\34\2\14\2\35\1\36\25\14\1\36\2\14\2\37"+
    "\1\40\25\14\1\40\1\14\43\0\1\41\23\0\2\17"+
    "\61\0\1\42\2\0\2\22\31\0\2\43\1\0\1\44"+
    "\27\0\2\43\45\0\1\45\16\0\2\46\31\0\2\46"+
    "\26\0\1\47\2\0\2\50\1\0\1\51\27\0\2\50"+
    "\31\0\2\52\1\0\1\53\27\0\2\52\31\0\2\54"+
    "\1\0\1\55\27\0\2\54\31\0\2\56\1\0\1\57"+
    "\27\0\2\56\41\0\1\60\52\0\1\61\2\0\2\62"+
    "\50\0\1\63\43\0\1\64\2\0\2\65\31\0\2\66"+
    "\31\0\2\67\31\0\2\70\42\0\1\71\51\0\1\72"+
    "\13\0\1\73\51\0\1\74\14\0\1\75\50\0\1\76"+
    "\16\0\1\77\46\0\1\100\14\0\1\101\50\0\1\102"+
    "\20\0\1\103\44\0\1\104\14\0\1\105\50\0\1\106"+
    "\21\0\1\107\43\0\1\110\14\0\1\111\50\0\1\112"+
    "\10\0\1\113\54\0\1\114\14\0\1\115\50\0\1\116"+
    "\16\0\1\117\46\0\1\120\11\0\1\121\53\0\1\122"+
    "\20\0\1\123\44\0\1\124\15\0\1\125\47\0\1\126"+
    "\14\0\1\127\50\0\1\130\11\0\1\131\53\0\1\132"+
    "\30\0\1\133\34\0\1\134\16\0\1\135\46\0\1\136"+
    "\15\0\1\137\47\0\1\140\17\0\1\141\45\0\1\142"+
    "\20\0\1\143\44\0\1\144\14\0\1\145\50\0\1\146"+
    "\33\0\1\147\31\0\1\150\12\0\1\151\52\0\1\152"+
    "\12\0\1\153\52\0\1\154\20\0\1\155\44\0\1\156"+
    "\13\0\1\157\51\0\1\160\12\0\1\161\41\0\1\162"+
    "\24\0\1\163\31\0\1\164\41\0\1\165\34\0\1\166"+
    "\31\0\1\167\24\0\1\170\32\0\1\171\32\0\1\172"+
    "\32\0\1\173\32\0\1\174\32\0\1\175\32\0\1\176"+
    "\32\0\1\177\41\0\1\200\21\0\1\201\37\0\1\202"+
    "\37\0\1\203\20\0\1\204\27\0\1\205\37\0\1\206"+
    "\32\0\1\207\32\0\1\210\32\0\1\211\35\0\1\212"+
    "\31\0\1\213\35\0\1\214\16\0\1\215\43\0\1\216"+
    "\41\0\1\217\27\0\1\220\36\0\1\221\32\0\1\222"+
    "\11\0\1\223\41\0\1\224\32\0\1\225\43\0\1\226"+
    "\34\0\1\227\33\0\1\230\25\0\1\231\15\0\1\232"+
    "\40\0\1\233\32\0\1\234\44\0\1\235\14\0\1\236"+
    "\52\0\1\237\12\0\1\240\33\0\1\241\35\0\1\242"+
    "\32\0\1\243\32\0\1\244\41\0\1\245\25\0\1\246"+
    "\42\0\1\247\35\0\1\250\2\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  1,  9,  1,  1, 
     9,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  1,  0,  0,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  public static boolean DEBUG = false;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public GMCSCFaLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public GMCSCFaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4050];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 53: 
          {  if (Settings.DEBUG) System.out.println("GMCSCFaFlex: ITER5");
   if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found float1");
   yybegin (ITER6);
    return new Symbol(GMCSCFaSym.FLOAT1);
 }
        case 169: break;
        case 111: 
          { 
               yybegin(DASH);
   }
        case 170: break;
        case 13: 
        case 14: 
          { 
     if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found the first integer in the iteration");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(ITER4);
   return new Symbol(GMCSCFaSym.INTCycle, new Integer(yytext())); }
        case 171: break;
        case 49: 
          { 
     if  (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found float4");
     yybegin(ITER);
      return new Symbol(GMCSCFaSym.FLOAT4); }
        case 172: break;
        case 54: 
          { 
  if  (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found float2");
  yybegin (ITER7);
   return new Symbol(GMCSCFaSym.FLOAT2);
 }
        case 173: break;
        case 55: 
          { 
     if  (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found float3");
     yybegin(ITER2);
      return new Symbol(GMCSCFaSym.FLOAT3); }
        case 174: break;
        case 16: 
        case 17: 
          { 
     if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found the second integer in the iteration");
     if (Settings.DEBUG) System.out.println(yytext());
     yybegin(ITER8); 
      return new Symbol(GMCSCFaSym.INT1, new Integer(yytext())); }
        case 175: break;
        case 117: 
          { 
  yybegin(IGNOREALL);
  return new Symbol(GMCSCFaSym.SCFDONE);
   }
        case 176: break;
        case 52: 
          { 
   if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found the energy");
   if (Settings.DEBUG) System.out.println(yytext());
   yybegin(ITER5);
   return new Symbol(GMCSCFaSym.ENERGY, new Float(yytext())); }
        case 177: break;
        case 21: 
        case 22: 
        case 23: 
          { if  (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found new line"); }
        case 178: break;
        case 109: 
          { 
       if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found the dash");
               yybegin(DASH); }
        case 179: break;
        case 37: 
          { 
   if  (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found float value");
  yybegin(ITER);  }
        case 180: break;
        case 167: 
          { 
    if (Settings.DEBUG) System.out.println("GMCSCFaFlex: Found START OF");
	   yybegin(ITER);
	   return new Symbol(GMCSCFaSym.FOUNDITER); 
   }
        case 181: break;
        case 30: 
        case 31: 
          {  }
        case 182: break;
        case 20: 
          {  }
        case 183: break;
        case 18: 
        case 19: 
          {  }
        case 184: break;
        case 15: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
          {  }
        case 185: break;
        case 11: 
        case 12: 
          {  }
        case 186: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] class_fields = sym.class.getFields();
      for (int i = 0; i < class_fields.length; i++) {
        if (class_fields[i].getInt(null) == token) {
          return class_fields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java GMCSCFaLexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        GMCSCFaLexer scanner = null;
        try {
          scanner = new GMCSCFaLexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
