/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Oct 24 22:02:16 CDT 2002
//----------------------------------------------------

package org.gridchem.client;
import java_cup.runtime.*;
import javax.swing.*;

import org.gridchem.client.*;
import org.gridchem.client.common.Settings;
import org.gridchem.client.util.*;

import java.util.*;
import java.io.*;

/** CUP v0.10j generated parser.
  * @version Thu Oct 24 22:02:16 CDT 2002
  */
public class GMCSCFaParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public GMCSCFaParser() {super();}

  /** Constructor which sets the default scanner. */
  public GMCSCFaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\003\005\000\002\002\004\000\002\004" +
    "\003\000\002\005\004\000\002\005\003\000\002\010\002" +
    "\000\002\006\012\000\002\007\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\004\004\005\001\002\000\004\011\012\001" +
    "\002\000\004\011\uffff\001\002\000\004\002\007\001\002" +
    "\000\004\002\000\001\002\000\006\005\023\011\012\001" +
    "\002\000\006\005\ufffd\011\ufffd\001\002\000\004\016\ufffc" +
    "\001\002\000\004\016\015\001\002\000\004\013\016\001" +
    "\002\000\004\013\ufffa\001\002\000\004\014\017\001\002" +
    "\000\004\015\020\001\002\000\004\006\021\001\002\000" +
    "\004\017\022\001\002\000\006\005\ufffb\011\ufffb\001\002" +
    "\000\004\002\001\001\002\000\006\005\ufffe\011\ufffe\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\003\005\004\003\001\001\000\006\005" +
    "\007\006\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\023\001\001\000\002\001" +
    "\001\000\004\010\012\001\001\000\004\007\013\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GMCSCFaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions() throws IOException
    {
      action_obj = new CUP$GMCSCFaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GMCSCFaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$GMCSCFaParser$actions {

 
  //__________________________________
  public static boolean DEBUG = true;
   public ParseGSCF2 temp;
  private static JTable table;               
  private static final String tableLabel = "SCF Intermediate Results:";
// private static String cycle = "0";
 
  
  public static JTable getTable() {
    return table;
  }

  public static String getTableLabel() {
    return tableLabel;
  }

/*  public static void main(String[] args) throws IOException {
     File temp = new File("temporary");
     boolean append = true;
     try{ 
     FileWriter temp1 = new FileWriter(temp, append);
     PrintWriter temp2 = new PrintWriter(temp1);}

     catch (FileNotFoundException e)  {
          System.out.println("no file, dude!");
       }  */
//   }

  private final GMCSCFaParser parser;

  /** Constructor */
  CUP$GMCSCFaParser$actions(GMCSCFaParser parser) throws IOException {
    this.parser = parser;
    //temp = new ParseGSCF2(Settings.defaultDirStr + 
   	temp = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary4");
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$GMCSCFaParser$do_action(
    int                        CUP$GMCSCFaParser$act_num,
    java_cup.runtime.lr_parser CUP$GMCSCFaParser$parser,
    java.util.Stack            CUP$GMCSCFaParser$stack,
    int                        CUP$GMCSCFaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GMCSCFaParser$result;

      /* select the action based on the action number */
      switch (CUP$GMCSCFaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // en ::= ENERGY 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gscfa:scfcycle:  ENERGY "+e); 
//   temp2.println(e);
//  parseSCF.putField("iteration "+cycle, "energy", e);
      float ener = e.floatValue();                                                             temp.putField(ener); 
 
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(5/*en*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // scfcycle ::= INTCycle NT$0 en FLOAT1 FLOAT2 FLOAT3 INT1 FLOAT4 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-6)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-7)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-7)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-7)).value;

              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(4/*scfcycle*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-7)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              Object RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gscfa:scfcycle:  ITERATION "+c);
   int cycle = c.intValue();
  temp.putField(cycle);
  temp.putField(", ");

//  temp2.print(c);
//   temp2.print(" "); 
//  cycle = c;
 
//  parseSCF.putField("iteration "+cycle, cycle);
 
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(6/*NT$0*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // scfpat ::= scfcycle 
            {
              Object RESULT = null;

              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // scfpat ::= scfpat scfcycle 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gscfa: in scfpat"); 
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // scfintro ::= FOUNDITER 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gscfa:  found start of SCF Iteration"); 
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(2/*scfintro*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= startpt EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-1)).value;
		RESULT = start_val;
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$GMCSCFaParser$parser.done_parsing();
          return CUP$GMCSCFaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // startpt ::= scfintro scfpat SCFDONE 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gscfa:  end of parse tree "); 
 	       table = new JTable();
	
//       table = parseSCF.getTable();
 	     
              CUP$GMCSCFaParser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$GMCSCFaParser$stack.elementAt(CUP$GMCSCFaParser$top-0)).right, RESULT);
            }
          return CUP$GMCSCFaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

