/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Sep 19 16:34:38 CDT 2002
//----------------------------------------------------

package org.gridchem.client;
import java_cup.runtime.*;
import javax.swing.*;

import org.gridchem.client.*;
import org.gridchem.client.common.Settings;
import org.gridchem.client.gui.panels.myccg.job.JobPanel;
import org.gridchem.client.util.*;

import java.util.*;
import java.io.*;

/** CUP v0.10j generated parser.
  * @version Thu Sep 19 16:34:38 CDT 2002
  */
public class GMP2OPTParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public GMP2OPTParser() {super();}

  /** Constructor which sets the default scanner. */
  public GMP2OPTParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\003\005\000\002\002\004\000\002\004" +
    "\003\000\002\005\004\000\002\005\003\000\002\012\002" +
    "\000\002\006\006\000\002\013\002\000\002\007\007\000" +
    "\002\010\004\000\002\011\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\004\004\005\001\002\000\004\007\011\001" +
    "\002\000\004\007\uffff\001\002\000\004\002\007\001\002" +
    "\000\004\002\000\001\002\000\006\005\027\007\011\001" +
    "\002\000\004\013\013\001\002\000\006\005\ufffd\007\ufffd" +
    "\001\002\000\004\006\ufffc\001\002\000\004\006\015\001" +
    "\002\000\004\012\017\001\002\000\006\005\ufffb\007\ufffb" +
    "\001\002\000\004\010\ufffa\001\002\000\004\010\021\001" +
    "\002\000\004\014\026\001\002\000\004\011\024\001\002" +
    "\000\006\005\ufff9\007\ufff9\001\002\000\004\015\025\001" +
    "\002\000\006\005\ufff7\007\ufff7\001\002\000\004\011\ufff8" +
    "\001\002\000\004\002\001\001\002\000\006\005\ufffe\007" +
    "\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\006\003\005\004\003\001\001\000\006\005" +
    "\007\006\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\027\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\013\001\001\000\004" +
    "\007\015\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\017\001\001\000\004\010\021\001\001\000\002" +
    "\001\001\000\004\011\022\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GMP2OPTParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions() throws IOException
    {
      action_obj = new CUP$GMP2OPTParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GMP2OPTParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$GMP2OPTParser$actions {

 
  //__________________________________
  public static boolean DEBUG = true;
     public ParseGSCF2 temp1;
    public ParseGSCF2 temp2;
   public ParseGSCF2 temp3;
  private static JTable table;               
  private static final String tableLabel = "SCF Intermediate Results:";
// private static String cycle = "0";
 
  
  public static JTable getTable() {
    return table;
  }

  public static String getTableLabel() {
    return tableLabel;
  }

//   }

  private final GMP2OPTParser parser;

  /** Constructor */
  CUP$GMP2OPTParser$actions(GMP2OPTParser parser) throws IOException {
    this.parser = parser;
    //temp1 = new ParseGSCF2(Settings.defaultDirStr + 
    		temp1 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "Energy_data");
    //temp2 = new ParseGSCF2(Settings.defaultDirStr + 
   	temp2 = new ParseGSCF2(Env.getApplicationDataDir() +
	       		Settings.fileSeparator + "temporary2");
    //temp3 = new ParseGSCF2(Settings.defaultDirStr + 
   	temp3 = new ParseGSCF2(Env.getApplicationDataDir() +
    		Settings.fileSeparator + "temporary3");
    temp1.putField("TitleText: Energy versus Iteration"+" - "+JobPanel.jobName+"\n");
    temp1.putField("XLabel: Iteration\n YLabel: Energy\n");
    temp1.putField("DataSet: Energy\n");
    temp1.putField("1, ");
    temp2.putField("TitleText: Gradient versus Iteration"+" - "+JobPanel.jobName+"\n");
    temp2.putField("XLabel: Iteration\n YLabel: Maximum Gradient\n");
    temp2.putField("DataSet: Maximum Gradient\n");
    temp3.putField("\n\n");
    temp3.putField("XLabel: Iteration\n YLabel: RMS Gradient\n");
    temp3.putField("DataSet: RMS Gradient\n");
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$GMP2OPTParser$do_action(
    int                        CUP$GMP2OPTParser$act_num,
    java_cup.runtime.lr_parser CUP$GMP2OPTParser$parser,
    java.util.Stack            CUP$GMP2OPTParser$stack,
    int                        CUP$GMP2OPTParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GMP2OPTParser$result;

      /* select the action based on the action number */
      switch (CUP$GMP2OPTParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // grad2 ::= RmsGrad RGRAD 
            {
              Object RESULT = null;
		int rgleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left;
		int rgright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right;
		Float rg = (Float)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt: RMS Force "+rg);
   float rms = rg.floatValue();
   temp3.putField(rms);

 
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(7/*grad2*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // grad1 ::= MaxGrad MGRAD 
            {
              Object RESULT = null;
		int mgleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left;
		int mgright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right;
		Float mg = (Float)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).value;
		 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt: Maximum Force "+mg);
   float maxim = mg.floatValue();
   temp2.putField(maxim);

              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(6/*grad1*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cycle ::= NSearch ITERATION NT$1 grad1 grad2 
            {
              Object RESULT = null;
              // propagate RESULT from NT$1
              if ( ((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-3)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-3)).value;

              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(5/*cycle*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$1 ::= 
            {
              Object RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt:  ITERATION "+c); 
        int cycl = c.intValue();
      temp1.putField(cycl+1);
      temp1.putField(", ");
      temp2.putField(cycl);
      temp2.putField(", ");
      temp3.putField(cycl);
      temp3.putField(", ");
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(9/*NT$1*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // scfcycle ::= Energ ENERGY NT$0 cycle 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).value;

              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(4/*scfcycle*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right;
		Float e = (Float)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).value;
 //___________________________________________________________________
   if (DEBUG) System.out.println("CUP:gopt:  ENERGY "+e);
             float energ = e.floatValue();
            energ = 100*energ;
            temp1.putField(energ);

              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(8/*NT$0*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // scfpat ::= scfcycle 
            {
              Object RESULT = null;

              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // scfpat ::= scfpat scfcycle 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt: in scfpat"); 
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(3/*scfpat*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // scfintro ::= FOUNDITER 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt:  found the start of Iteration"); 
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(2/*scfintro*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= startpt EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).value;
		RESULT = start_val;
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$GMP2OPTParser$parser.done_parsing();
          return CUP$GMP2OPTParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // startpt ::= scfintro scfpat SCFDONE 
            {
              Object RESULT = null;
		 if (DEBUG) System.out.println("CUP:gopt:  end of parse tree "); 
 	       table = new JTable();
	
//       table = parseSCF.getTable();
 	     
              CUP$GMP2OPTParser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$GMP2OPTParser$stack.elementAt(CUP$GMP2OPTParser$top-0)).right, RESULT);
            }
          return CUP$GMP2OPTParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

