package org.gridchem.client;
/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 23:09:54 CST 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class MP2to5dSym {
  /* terminals */
  public static final int E4_SDTQ = 8;
  public static final int MP2OPT = 16;
  public static final int LIM = 18;
  public static final int UMP4_SDQ = 11;
  public static final int UMP4_SDTQ = 12;
  public static final int E4_DQ = 6;
  public static final int FCOPT = 13;
  public static final int UMP4_DQ = 10;
  public static final int E4_SDQ = 7;
  public static final int E3 = 5;
  public static final int E2 = 2;
  public static final int FLOAT = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MP4_T = 4;
  public static final int FCOPT2 = 14;
  public static final int ALGOPT = 15;
  public static final int VAR = 17;
  public static final int EUMP3 = 9;
  public static final int EUMP2 = 3;
}

