/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 23:09:24 CST 2005
//----------------------------------------------------

package org.gridchem.client;
import org.gridchem.client.*;
import org.gridchem.client.common.Settings;

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Wed Jan 26 23:09:24 CST 2005
  */
public class MP2to5bParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MP2to5bParser() {super();}

  /** Constructor which sets the default scanner. */
  public MP2to5bParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\005\000\002\003\004\000\002\002\004\000\002\003" +
    "\003\000\002\004\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\007\000\006\017\004\020\005\001\002\000\010\002" +
    "\ufffe\017\ufffe\020\ufffe\001\002\000\010\002\ufffd\017\ufffd" +
    "\020\ufffd\001\002\000\010\002\uffff\017\uffff\020\uffff\001" +
    "\002\000\010\002\011\017\004\020\005\001\002\000\010" +
    "\002\001\017\001\020\001\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\007\000\006\003\006\004\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\007" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MP2to5bParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MP2to5bParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MP2to5bParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 if(Settings.DEBUG) System.out.println("CUP:mp2to5b:  entry"); 
    }

 ///public static boolean DEBUG = false; 
}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MP2to5bParser$actions {
  private final MP2to5bParser parser;

  /** Constructor */
  CUP$MP2to5bParser$actions(MP2to5bParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MP2to5bParser$do_action(
    int                        CUP$MP2to5bParser$act_num,
    java_cup.runtime.lr_parser CUP$MP2to5bParser$parser,
    java.util.Stack            CUP$MP2to5bParser$stack,
    int                        CUP$MP2to5bParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MP2to5bParser$result;

      /* select the action based on the action number */
      switch (CUP$MP2to5bParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // element ::= FCOPT2 
            {
              Object RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).value;
		 if(Settings.DEBUG) System.out.println("CUP:mp2to5b:  Frozen Core Option:  "+s);
	   ParseMP2to5.put("Frozen Core Option?  (Check raw output)  ", s); 
              CUP$MP2to5bParser$result = new java_cup.runtime.Symbol(2/*element*/, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right, RESULT);
            }
          return CUP$MP2to5bParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // element ::= FCOPT 
            {
              Object RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).value;
		 if(Settings.DEBUG) System.out.println("CUP:mp2to5b:  Frozen Core Option:  "+s);
	   ParseMP2to5.put("Frozen Core Option:  ", s); 
              CUP$MP2to5bParser$result = new java_cup.runtime.Symbol(2/*element*/, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right, RESULT);
            }
          return CUP$MP2to5bParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // startpt ::= element 
            {
              Object RESULT = null;

              CUP$MP2to5bParser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right, RESULT);
            }
          return CUP$MP2to5bParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= startpt EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-1)).value;
		RESULT = start_val;
              CUP$MP2to5bParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MP2to5bParser$parser.done_parsing();
          return CUP$MP2to5bParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // startpt ::= startpt element 
            {
              Object RESULT = null;

              CUP$MP2to5bParser$result = new java_cup.runtime.Symbol(1/*startpt*/, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MP2to5bParser$stack.elementAt(CUP$MP2to5bParser$top-0)).right, RESULT);
            }
          return CUP$MP2to5bParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

