package org.gridchem.client;
/*Copyright (c) 2004,University of Illinois at Urbana-Champaign.  All rights reserved.

Developed by:
Chemistry and Computational Biology Group

NCSA, University of Illinois at Urbana-Champaign

http://ncsa.uiuc.edu/GridChem

Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation
files (the "Software") to deal with the Software without
restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom 
the Software is furnished to do so, subject to the following 
conditions:
1. Redistributions of source code must retain the above copyright notice, 
   this list of conditions and the following disclaimers.
2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimers in the documentation
   and/or other materials provided with the distribution.
3. Neither the names of Chemistry and Computational Biology Group , NCSA, 
   University of Illinois at Urbana-Champaign, nor the names of its contributors 
   may be used to endorse or promote products derived from this Software without 
   specific prior written permission.
    
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  
IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS WITH THE SOFTWARE.

*/

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 23:16:21 CST 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SCFbSym {
  /* terminals */
  public static final int TEE = 12;
  public static final int EQUALS = 34;
  public static final int PE = 32;
  public static final int GTEF = 20;
  public static final int INT = 37;
  public static final int LEAVE = 36;
  public static final int LTEF = 19;
  public static final int SCFDONE = 25;
  public static final int CONVG = 27;
  public static final int DUMMY = 35;
  public static final int IS = 15;
  public static final int PASS = 5;
  public static final int ERR = 21;
  public static final int MAXDP = 23;
  public static final int S2 = 28;
  public static final int ATCYCLE = 10;
  public static final int IE = 16;
  public static final int EOF = 0;
  public static final int COEFF = 11;
  public static final int RMSDP = 22;
  public static final int IDIAG = 6;
  public static final int error = 1;
  public static final int ERHF = 26;
  public static final int NO09 = 17;
  public static final int FOUNDLENX = 3;
  public static final int COLON = 24;
  public static final int GAP = 13;
  public static final int DELTAE = 8;
  public static final int NK = 14;
  public static final int EE = 33;
  public static final int DIIS = 9;
  public static final int LENXINT = 38;
  public static final int FLOAT = 39;
  public static final int KE = 31;
  public static final int MINUSVT = 29;
  public static final int NV01 = 18;
  public static final int AU = 30;
  public static final int FOUNDSCF = 2;
  public static final int CYCLE = 4;
  public static final int ENERGY = 7;
}

